spring.application.name=microservicio-demo
server.port=8082
# --- Configuración de Conexión a MySQL ---
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.url=jdbc:mysql://mysql_testing:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuración de JPA/Hibernate ---
# Muestra las consultas SQL en la consola (útil para debug)
spring.jpa.show-sql=true
# Configura Hibernate para que no haga cambios automáticos en el esquema (o 'update' si estás empezando)
spring.jpa.hibernate.ddl-auto=none
